
CREATE DATABASE IF NOT EXISTS POWER_SERVICE;
USE POWER_SERVICE;

CREATE TABLE IF NOT EXISTS POSTAL_CODES_TABLE(
	POSTAL_CODE VARCHAR(6) PRIMARY KEY,
    POPULATION INT NOT NULL,
    AREA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS DISTRIBUTION_HUBS_TABLE(
	HUB_ID VARCHAR(256) PRIMARY KEY,
    LOCATION_X INT  NOT NULL,
    LOCATION_Y INT  NOT NULL,
    IN_SERVICE BOOL NOT NULL DEFAULT TRUE,
    REPAIR_ESTIMATE FLOAT NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS POSTAL_CODES_DISTRIBUTION_HUBS_TABLE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    POSTAL_CODE VARCHAR(6) NOT NULL,
	HUB_ID VARCHAR(256) NOT NULL,
    FOREIGN KEY(POSTAL_CODE) REFERENCES POSTAL_CODES_TABLE(POSTAL_CODE),
	FOREIGN KEY(HUB_ID) REFERENCES DISTRIBUTION_HUBS_TABLE(HUB_ID),
	UNIQUE(POSTAL_CODE, HUB_ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES_TABLE(
    EMPLOYEE_ID VARCHAR(256) PRIMARY KEY,
	FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) 
);

CREATE TABLE IF NOT EXISTS HUB_REPAIR_TABLE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    HUB_ID VARCHAR(256) NOT NULL,
    EMPLOYEE_ID VARCHAR(256) NOT NULL,
	REPAIR_TIME FLOAT NOT NULL,
    IN_SERVICE BOOL NOT NULL,
    TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(HUB_ID) REFERENCES DISTRIBUTION_HUBS_TABLE(HUB_ID),
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES_TABLE(EMPLOYEE_ID)
);

-- insert dummy employees
INSERT INTO EMPLOYEES_TABLE VALUES
("e1", "John", "Cena"),
("e2", "Seth", "Rollins"),
("e3", "Brock", "Lesnar"),
("e4", "Randy", "Orton");


-- drop table POSTAL_CODES_DISTRIBUTION_HUBS_TABLE;
-- drop table HUB_REPAIR_TABLE;
-- drop table EMPLOYEES_TABLE;
-- drop table POSTAL_CODES_TABLE;
-- drop table DISTRIBUTION_HUBS_TABLE;